### PR TITLE
fix: download directories outside of MFS

### LINKED ISSUE #1829: Downloading a file does not work (empty queue)
**Describe the bug**
I opened a CID which is a folder with one file in it. I clicked on the menu-dots of the file, and selected "download". A in-website window appeared with the headline "imported 0 items".

Either the UI is broken, and there's a download going on, or there's no reaction of the ipfs node.

I don't use the desktop application on this system, but a system service where the Browser-Plugin/Webbrowser connects to.

**To Reproduce**
1. Click on the browser add-on
2. Select My Node
3. Navigate to the Files tab
4. Paste the CID bafykbzacedyo7klhyzgzekwpxvuxrqihsl4rcgzpvxcrptyoqf43ruio3buis into the search bar
5. Click on the browse button
6. Select the "..."-menu of the one file
7. Click on "Download"

**Expected behavior**
Have a button labeled "Download to Node" and a download progress bar OR have a Download start in the Webbrowser.

**Screenshots**
Screenshot_20210727_111436-1

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Browser Version: Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
 - Version UI: v2.12.4

### PR DESCRIPTION
**Pull request by hacdias**
Fixes #1829.

I went with a simpler approach than https://github.com/ipfs/ipfs-webui/issues/1814#issuecomment-873000366 (suggested fix) because the API is POST-only, so creating a link and then "opening" it would have returned a 405 error.

When https://github.com/ipfs/go-ipfs/issues/8234 is merged, #1814 can be addressed. In the meanwhile, #1829 is easily fixed.

The failing tests are the same as in the main branch.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

File: src/lib/files.js [hunk 1]
```diff
@@ -46,11 +46,12 @@ export function normalizeFiles (files) {
  * @returns {Promise<FileDownload>}
  */
 async function downloadSingle (file, gatewayUrl, apiUrl) {
-  let url, filename, method
+  let url, filename, name, method
```
Comment (rafaelramalho19) [inline src/lib/files.js:49]: No need to make `name`  a variable up here when you're only using it in line 53.

**Review by rafaelramalho19 — APPROVED** [review]

**Comment by lidel** [comment]
lgtm, thanks!
